name: "godot gut ci test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Godot GUT CI Test
        uses: ./
        with:
          godot_version: 3.2.2
          gut_params: -gdir=res://tests/unit
          working_dir: test-project/
